name: Build Docs
run-name: Build Docs
on:
  push:
    branches:
      - "*"
    paths:
      - "doc/**"
jobs:
  docs:
    name: Build docs CI
    runs-on: ubuntu-latest
    steps:
      - name: Build docs on server
        run: curl -fsS "http://www.diving-fish.com:8333/ci/doc_build?sha=${{ github.sha }}&token=${{ secrets.CI_TOKEN }}"